import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="h-[8dvh] flex items-center justify-start bg-zinc-900 px-6">
          <nav>
            <h1>Test <span className="text-sky-600">Nube</span></h1>
          </nav>
        </header>
        <main className="h-[86dvh] p-6 overflow-auto ">{children}</main>
        <footer className="h-[6dvh] flex items-center justify-end bg-zinc-900 px-6" >
          <small>© 2023 TestNube</small>
        </footer>
      </body>
    </html>
  );
}
